import {
  BarChart3,
  BookOpen,
  CalendarCheck,
  CalendarDays,
  ChefHat,
  ClipboardList,
  Gift,
  Inbox,
  LayoutDashboard,
  LayoutGrid,
  type LucideIcon,
  Megaphone,
  MessageSquareText,
  Receipt,
  Settings2,
  Sparkles,
  Stamp,
  Star,
  Tags,
  Users,
  UsersRound,
  UtensilsCrossed,
  Workflow,
  Zap,
} from 'lucide-react'
import type { FeatureKey } from '@/lib/platform/features'
import type { TenantRole } from '@/lib/tenant/types'

export type CommandActionType = 'navigate' | 'navigate-new'

export type CommandEntry = {
  id: string
  label: string
  icon: LucideIcon
  group: 'Acciones rápidas' | 'Ir a' | 'Operación'
  type: CommandActionType
  /** Devuelve el path destino dado el slug. */
  href: (slug: string) => string
  /** Para narrow keyword search en cmdk. */
  keywords?: string[]
  /** Si está, sólo se muestra cuando la feature está ON (o quien mira es superadmin). */
  feature?: FeatureKey
  /**
   * Roles que ven la entrada. Default: solo owner (fail-closed: el palette es
   * mayormente territorio del dueño; los roles acotados suman lo suyo explícito).
   */
  roles?: TenantRole[]
}

export const commandEntries: CommandEntry[] = [
  // Acciones rápidas (mutaciones / new resource)
  {
    id: 'new-customer',
    label: 'Nuevo cliente',
    icon: Users,
    group: 'Acciones rápidas',
    type: 'navigate-new',
    href: (s) => `/${s}/clientes/nuevo`,
    keywords: ['cliente', 'persona', 'agregar', 'crear'],
  },
  {
    id: 'new-reservation',
    label: 'Nueva reserva',
    icon: CalendarCheck,
    group: 'Acciones rápidas',
    type: 'navigate-new',
    href: (s) => `/${s}/reservas/nuevo`,
    keywords: ['reserva', 'mesa', 'agendar', 'crear'],
    roles: ['owner', 'host'],
  },
  {
    id: 'new-broadcast',
    label: 'Nueva difusión',
    icon: Megaphone,
    group: 'Acciones rápidas',
    type: 'navigate-new',
    href: (s) => `/${s}/mensajeria/difusiones/nueva`,
    keywords: ['enviar', 'whatsapp', 'broadcast', 'campaña'],
  },
  {
    id: 'new-event',
    label: 'Programar evento',
    icon: CalendarDays,
    group: 'Acciones rápidas',
    type: 'navigate-new',
    href: (s) => `/${s}/eventos/programados/nuevo`,
    keywords: ['fecha', 'agenda', 'show', 'fiesta', 'calendario'],
    roles: ['owner', 'host'],
  },
  {
    id: 'new-flow',
    label: 'Nuevo flow',
    icon: Workflow,
    group: 'Acciones rápidas',
    type: 'navigate-new',
    href: (s) => `/${s}/mensajeria/flows/nuevo`,
    keywords: ['automatización', 'recurrente'],
  },
  {
    id: 'close-table-legacy',
    label: 'Cerrar mesa (legacy)',
    icon: Receipt,
    group: 'Acciones rápidas',
    type: 'navigate',
    href: (s) => `/${s}/visitas/nueva`,
    keywords: ['cerrar', 'mesa', 'cobrar'],
    feature: 'table_service',
  },

  // Operación (turno en vivo)
  {
    id: 'live-sessions',
    label: 'Salón en vivo',
    icon: ClipboardList,
    group: 'Operación',
    type: 'navigate',
    href: (s) => `/${s}/salon/mesas`,
    keywords: ['mesas', 'sesiones', 'salón', 'live'],
    feature: 'table_service',
  },
  {
    id: 'kitchen',
    label: 'Cocina',
    icon: ChefHat,
    group: 'Operación',
    type: 'navigate',
    href: (s) => `/${s}/salon/cocina`,
    keywords: ['kitchen', 'tickets', 'pedidos'],
    feature: 'kitchen',
  },
  {
    id: 'inbox',
    label: 'Inbox',
    icon: Inbox,
    group: 'Operación',
    type: 'navigate',
    href: (s) => `/${s}/mensajeria/inbox`,
    keywords: ['mensajes', 'whatsapp', 'instagram', 'inbox', 'bandeja', 'mensajeria'],
  },

  // Ir a (navegación)
  {
    id: 'operativo',
    label: 'Operativo',
    icon: ClipboardList,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/operativo`,
    keywords: ['hoy', 'timeline', 'llegadas', 'dia'],
    roles: ['owner', 'host'],
  },
  {
    id: 'my-numbers',
    label: 'Mis números',
    icon: BarChart3,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/mis-numeros`,
    keywords: ['comisiones', 'ganancias', 'plata', 'liquidacion'],
    roles: ['host'],
  },
  {
    id: 'home',
    label: 'Resumen',
    icon: LayoutDashboard,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}`,
    keywords: ['dashboard', 'home', 'inicio'],
  },
  {
    id: 'people',
    label: 'Personas',
    icon: Users,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/clientes`,
    keywords: ['clientes', 'crm'],
  },
  {
    id: 'audiences',
    label: 'Audiencias',
    icon: UsersRound,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/mensajeria/audiencias`,
    keywords: ['segmentos', 'filtros'],
  },
  {
    id: 'broadcasts',
    label: 'Difusiones',
    icon: Megaphone,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/mensajeria/difusiones`,
    keywords: ['campañas', 'whatsapp'],
  },
  {
    id: 'flows',
    label: 'Flows',
    icon: Workflow,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/mensajeria/flows`,
    keywords: ['automatización'],
  },
  {
    id: 'calendar',
    label: 'Calendario',
    icon: CalendarDays,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/eventos/programados`,
    keywords: [
      'agenda',
      'mes',
      'sushi libre',
      'pizza libre',
      'cupos',
      'eventos',
      'fiesta',
      'show',
      'peña',
    ],
    roles: ['owner', 'host'],
  },
  {
    id: 'reservations',
    label: 'Reservas',
    icon: CalendarDays,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/reservas`,
    keywords: ['reserva', 'mesa', 'reservar'],
    roles: ['owner', 'host'],
  },
  {
    id: 'menu',
    label: 'Carta',
    icon: UtensilsCrossed,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/menu`,
    keywords: ['menu', 'carta', 'productos', 'items', 'fotos'],
    roles: ['owner', 'editor'],
  },
  {
    id: 'club',
    label: 'Club de beneficios',
    icon: Star,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/club?tab=programa`,
    keywords: ['fidelizacion', 'lealtad', 'loyalty', 'beneficios'],
  },
  {
    id: 'tiers',
    label: 'Niveles del club',
    icon: Sparkles,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/club?tab=programa`,
    keywords: ['vip', 'tiers', 'escalones', 'club'],
  },
  {
    id: 'points',
    label: 'Puntos y recompensas',
    icon: Gift,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/club?tab=programa`,
    keywords: ['fidelidad', 'rewards', 'recompensas', 'club'],
  },
  {
    id: 'punch-cards',
    label: 'Punch cards',
    icon: Stamp,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/club?tab=punch`,
    keywords: ['tarjetas', 'sellos', 'club'],
  },
  {
    id: 'welcome-gift',
    label: 'Regalo de bienvenida',
    icon: Star,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/club?tab=bienvenida`,
    keywords: ['bienvenida', 'welcome', 'regalo', 'club'],
  },
  {
    id: 'tags',
    label: 'Tags de carta',
    icon: Tags,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/menu/tags`,
    keywords: ['etiquetas'],
    roles: ['owner', 'editor'],
  },
  {
    id: 'floor-plan',
    label: 'Plano del salón',
    icon: LayoutGrid,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/local/mesas`,
    keywords: ['mesas', 'floor', 'plano', 'salón'],
    feature: 'floor_plan',
  },
  {
    id: 'auto-accept',
    label: 'Auto-aceptación',
    icon: Zap,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/local/auto-aceptacion`,
    keywords: ['settings'],
    feature: 'auto_accept',
  },
  {
    id: 'templates',
    label: 'Plantillas WhatsApp',
    icon: MessageSquareText,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/mensajeria/plantillas`,
    keywords: ['mensajes', 'plantillas'],
  },
  {
    id: 'team',
    label: 'Equipo',
    icon: UsersRound,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/configuracion/equipo`,
    keywords: ['staff', 'invitar'],
  },
  {
    id: 'stats',
    label: 'Estadísticas',
    icon: BarChart3,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/estadisticas`,
    keywords: ['reportes', 'analytics'],
  },
  {
    id: 'docs',
    label: 'Documentación',
    icon: BookOpen,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/docs`,
    keywords: ['ayuda', 'guía', 'manual', 'help'],
  },
  {
    id: 'settings',
    label: 'Configuración',
    icon: Settings2,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/configuracion`,
    keywords: ['ajustes', 'preferencias'],
  },
]
