import {
  BarChart3,
  BookOpen,
  CalendarDays,
  ChefHat,
  ClipboardList,
  Inbox,
  LayoutDashboard,
  LayoutGrid,
  type LucideIcon,
  Megaphone,
  MessageSquareText,
  Receipt,
  Settings2,
  Stamp,
  Star,
  Tags,
  Users,
  UsersRound,
  UtensilsCrossed,
  Workflow,
  Zap,
} from 'lucide-react'
import type { FeatureKey } from '@/lib/platform/features'

export type CommandActionType = 'navigate' | 'navigate-new'

export type CommandEntry = {
  id: string
  label: string
  icon: LucideIcon
  group: 'Acciones rápidas' | 'Ir a' | 'Operación'
  type: CommandActionType
  /** Devuelve el path destino dado el slug. */
  href: (slug: string) => string
  /** Para narrow keyword search en cmdk. */
  keywords?: string[]
  /** Si está, sólo se muestra cuando la feature está ON (o quien mira es superadmin). */
  feature?: FeatureKey
}

export const commandEntries: CommandEntry[] = [
  // Acciones rápidas (mutaciones / new resource)
  {
    id: 'new-customer',
    label: 'Nuevo cliente',
    icon: Users,
    group: 'Acciones rápidas',
    type: 'navigate-new',
    href: (s) => `/${s}/clientes/nuevo`,
    keywords: ['cliente', 'persona', 'agregar', 'crear'],
  },
  {
    id: 'new-broadcast',
    label: 'Nueva difusión',
    icon: Megaphone,
    group: 'Acciones rápidas',
    type: 'navigate-new',
    href: (s) => `/${s}/difusiones/nueva`,
    keywords: ['enviar', 'whatsapp', 'broadcast', 'campaña'],
  },
  {
    id: 'new-event',
    label: 'Nuevo evento',
    icon: CalendarDays,
    group: 'Acciones rápidas',
    type: 'navigate-new',
    href: (s) => `/${s}/eventos/nuevo`,
    keywords: ['fecha', 'agenda', 'show', 'fiesta'],
  },
  {
    id: 'new-flow',
    label: 'Nuevo flow',
    icon: Workflow,
    group: 'Acciones rápidas',
    type: 'navigate-new',
    href: (s) => `/${s}/flows/nuevo`,
    keywords: ['automatización', 'recurrente'],
  },
  {
    id: 'close-table-legacy',
    label: 'Cerrar mesa (legacy)',
    icon: Receipt,
    group: 'Acciones rápidas',
    type: 'navigate',
    href: (s) => `/${s}/visitas/nueva`,
    keywords: ['cerrar', 'mesa', 'cobrar'],
    feature: 'table_service',
  },

  // Operación (turno en vivo)
  {
    id: 'live-sessions',
    label: 'Salón en vivo',
    icon: ClipboardList,
    group: 'Operación',
    type: 'navigate',
    href: (s) => `/${s}/salon/mesas`,
    keywords: ['mesas', 'sesiones', 'salón', 'live'],
    feature: 'table_service',
  },
  {
    id: 'kitchen',
    label: 'Cocina',
    icon: ChefHat,
    group: 'Operación',
    type: 'navigate',
    href: (s) => `/${s}/salon/cocina`,
    keywords: ['kitchen', 'tickets', 'pedidos'],
    feature: 'kitchen',
  },
  {
    id: 'inbox',
    label: 'Bandeja',
    icon: Inbox,
    group: 'Operación',
    type: 'navigate',
    href: (s) => `/${s}/bandeja`,
    keywords: ['mensajes', 'whatsapp', 'instagram', 'inbox'],
  },

  // Ir a (navegación)
  {
    id: 'home',
    label: 'Resumen',
    icon: LayoutDashboard,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}`,
    keywords: ['dashboard', 'home', 'inicio'],
  },
  {
    id: 'people',
    label: 'Personas',
    icon: Users,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/clientes`,
    keywords: ['clientes', 'crm'],
  },
  {
    id: 'audiences',
    label: 'Audiencias',
    icon: UsersRound,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/audiencias`,
    keywords: ['segmentos', 'filtros'],
  },
  {
    id: 'broadcasts',
    label: 'Difusiones',
    icon: Megaphone,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/difusiones`,
    keywords: ['campañas', 'whatsapp'],
  },
  {
    id: 'flows',
    label: 'Flows',
    icon: Workflow,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/flows`,
    keywords: ['automatización'],
  },
  {
    id: 'calendar',
    label: 'Calendario',
    icon: CalendarDays,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/eventos/programados`,
    keywords: ['agenda', 'mes', 'sushi libre', 'pizza libre', 'cupos', 'eventos programados'],
  },
  {
    id: 'reservations',
    label: 'Reservas',
    icon: CalendarDays,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/reservas`,
    keywords: ['reserva', 'mesa', 'reservar'],
  },
  {
    id: 'events',
    label: 'Shows y fiestas',
    icon: CalendarDays,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/eventos`,
    keywords: ['eventos', 'fiesta', 'show', 'peña', 'cena tematica', 'marketing'],
  },
  {
    id: 'menu',
    label: 'Menú',
    icon: UtensilsCrossed,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/menu`,
    keywords: ['carta', 'productos', 'items'],
  },
  {
    id: 'points',
    label: 'Puntos',
    icon: Star,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/puntos`,
    keywords: ['fidelidad', 'rewards'],
  },
  {
    id: 'punch-cards',
    label: 'Punch cards',
    icon: Stamp,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/punch-cards`,
    keywords: ['tarjetas', 'sellos'],
  },
  {
    id: 'tags',
    label: 'Tags de carta',
    icon: Tags,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/configuracion/tags`,
    keywords: ['etiquetas'],
  },
  {
    id: 'floor-plan',
    label: 'Plano del salón',
    icon: LayoutGrid,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/local/mesas`,
    keywords: ['mesas', 'floor', 'plano', 'salón'],
    feature: 'floor_plan',
  },
  {
    id: 'auto-accept',
    label: 'Auto-aceptación',
    icon: Zap,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/local/auto-aceptacion`,
    keywords: ['settings'],
    feature: 'auto_accept',
  },
  {
    id: 'templates',
    label: 'Plantillas WhatsApp',
    icon: MessageSquareText,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/configuracion/templates`,
    keywords: ['mensajes', 'plantillas'],
  },
  {
    id: 'team',
    label: 'Equipo',
    icon: UsersRound,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/configuracion/equipo`,
    keywords: ['staff', 'invitar'],
  },
  {
    id: 'stats',
    label: 'Estadísticas',
    icon: BarChart3,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/estadisticas`,
    keywords: ['reportes', 'analytics'],
  },
  {
    id: 'docs',
    label: 'Documentación',
    icon: BookOpen,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/docs`,
    keywords: ['ayuda', 'guía', 'manual', 'help'],
  },
  {
    id: 'settings',
    label: 'Configuración',
    icon: Settings2,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/configuracion`,
    keywords: ['ajustes', 'preferencias'],
  },
]
