import {
  ArrowLeftRight,
  Banknote,
  BarChart3,
  BookOpen,
  BookText,
  CalendarCheck,
  CalendarCheck2,
  CalendarDays,
  ChefHat,
  ClipboardList,
  Coins,
  FileCode2,
  FileDown,
  FilePlus2,
  Gift,
  HandCoins,
  Inbox,
  Landmark,
  LayoutDashboard,
  LayoutGrid,
  Link2,
  ListChecks,
  ListTree,
  type LucideIcon,
  Map as MapIcon,
  Megaphone,
  MessageSquareText,
  PartyPopper,
  PlugZap,
  QrCode,
  Receipt,
  ReceiptText,
  Scale,
  ScanLine,
  Settings2,
  Sparkles,
  Stamp,
  Star,
  Tags,
  Truck,
  Users,
  UsersRound,
  UtensilsCrossed,
  Wallet,
  Workflow,
  Zap,
} from 'lucide-react'
import type { AccountingAction } from '@/components/administracion/acciones/types'
import type { FeatureKey } from '@/lib/platform/features'
import type { TenantRole } from '@/lib/tenant/types'

export type CommandActionType = 'navigate' | 'navigate-new'

export type CommandEntry = {
  id: string
  label: string
  icon: LucideIcon
  group: 'Acciones rápidas' | 'Administración' | 'Ir a' | 'Operación'
  type: CommandActionType
  /** Devuelve el path destino dado el slug. */
  href: (slug: string) => string
  /** Para narrow keyword search en cmdk. */
  keywords?: string[]
  /** Si está, sólo se muestra cuando la feature está ON (o quien mira es superadmin). */
  feature?: FeatureKey
  /**
   * Roles que ven la entrada. Default: solo owner (fail-closed: el palette es
   * mayormente territorio del dueño; los roles acotados suman lo suyo explícito).
   */
  roles?: TenantRole[]
  /**
   * Administración (H.0): el acceso por persona que hace falta. `write` =
   * cargar (solo dueños habilitados); `read` = ver (también la contadora);
   * `read_or_setup` = además el dueño que puede hacer la puesta en marcha.
   */
  accounting?: 'read' | 'write' | 'read_or_setup'
  /**
   * Abre una hoja de acción rápida (`?accion=`) sobre la pantalla actual si ya
   * se está en Administración; si no, sobre el Resumen. Gana sobre `href`.
   */
  accountingAction?: AccountingAction
}

const ACC_KEYWORDS = ['contable', 'contabilidad', 'administracion', 'administración']

/** Las entradas de Administración (H.0): acciones de carga y navegación. */
const accountingEntries: CommandEntry[] = [
  // Acciones (dueños con acceso de escritura)
  {
    id: 'acc-new-expense',
    label: 'Nuevo gasto',
    icon: Receipt,
    group: 'Administración',
    type: 'navigate',
    href: (s) => `/${s}/administracion?accion=gasto`,
    accountingAction: 'gasto',
    keywords: ['gasto', 'compra', 'ticket', 'pague', 'pagué', 'compre', 'compré', ...ACC_KEYWORDS],
    accounting: 'write',
  },
  {
    id: 'acc-sales-close',
    label: 'Cierre del día',
    icon: CalendarCheck2,
    group: 'Administración',
    type: 'navigate',
    href: (s) => `/${s}/administracion/ventas/cierre`,
    keywords: ['cierre', 'ventas', 'caja', 'thinkeon', 'z', ...ACC_KEYWORDS],
    accounting: 'write',
  },
  {
    id: 'acc-pay',
    label: 'Pagar a un proveedor',
    icon: Banknote,
    group: 'Administración',
    type: 'navigate',
    href: (s) => `/${s}/administracion?accion=pagar`,
    accountingAction: 'pagar',
    keywords: ['pago', 'pagar', 'proveedor', 'orden de pago', 'deuda', ...ACC_KEYWORDS],
    accounting: 'write',
  },
  {
    id: 'acc-collect',
    label: 'Registrar un cobro',
    icon: HandCoins,
    group: 'Administración',
    type: 'navigate',
    href: (s) => `/${s}/administracion?accion=cobrar`,
    accountingAction: 'cobrar',
    keywords: [
      'cobro',
      'acreditacion',
      'acreditación',
      'liquidacion',
      'liquidación',
      'posnet',
      'pedidosya',
      'rappi',
      ...ACC_KEYWORDS,
    ],
    accounting: 'write',
  },
  {
    id: 'acc-transfer',
    label: 'Mover plata',
    icon: ArrowLeftRight,
    group: 'Administración',
    type: 'navigate',
    href: (s) => `/${s}/administracion?accion=mover`,
    accountingAction: 'mover',
    keywords: [
      'transferir',
      'transferencia',
      'depositar',
      'deposito',
      'depósito',
      'retirar',
      ...ACC_KEYWORDS,
    ],
    accounting: 'write',
  },
  {
    id: 'acc-adjust',
    label: 'Ajustar saldo de una caja',
    icon: Scale,
    group: 'Administración',
    type: 'navigate',
    href: (s) => `/${s}/administracion?accion=ajustar`,
    accountingAction: 'ajustar',
    keywords: ['arqueo', 'contar caja', 'mercado pago', 'saldo', 'diferencia', ...ACC_KEYWORDS],
    accounting: 'write',
  },
  {
    id: 'acc-other-movement',
    label: 'Otro ingreso o egreso',
    icon: Wallet,
    group: 'Administración',
    type: 'navigate',
    href: (s) => `/${s}/administracion?accion=movimiento`,
    accountingAction: 'movimiento',
    keywords: ['ingreso', 'egreso', 'retiro', 'aporte', 'socio', 'efectivo', ...ACC_KEYWORDS],
    accounting: 'write',
  },
  {
    id: 'acc-new-purchase',
    label: 'Nueva factura de proveedor',
    icon: FilePlus2,
    group: 'Administración',
    type: 'navigate',
    href: (s) => `/${s}/administracion/compras/nueva`,
    keywords: [
      'factura',
      'compra',
      'proveedor',
      'nota de credito',
      'nota de crédito',
      ...ACC_KEYWORDS,
    ],
    accounting: 'write',
  },
  {
    id: 'acc-bank-expense',
    label: 'Gasto bancario',
    icon: Landmark,
    group: 'Administración',
    type: 'navigate',
    href: (s) => `/${s}/administracion/cajas/gasto-bancario`,
    keywords: [
      'banco',
      'comision',
      'comisión',
      'impuesto',
      'debito',
      'débito',
      'sircreb',
      ...ACC_KEYWORDS,
    ],
    accounting: 'write',
  },
  {
    id: 'acc-manual-entry',
    label: 'Asiento manual',
    icon: BookText,
    group: 'Administración',
    type: 'navigate',
    href: (s) => `/${s}/administracion/libros/asiento-manual`,
    keywords: ['asiento', 'ajuste', 'sueldos', 'debe', 'haber', ...ACC_KEYWORDS],
    accounting: 'write',
  },
  {
    id: 'acc-close-month',
    label: 'Cerrar el mes',
    icon: CalendarCheck,
    group: 'Administración',
    type: 'navigate',
    href: (s) => `/${s}/administracion/libros/cierres`,
    keywords: ['cierre', 'mes', 'cerrar', 'iva', ...ACC_KEYWORDS],
    accounting: 'write',
  },

  // Navegación (dueños habilitados y contadora)
  {
    id: 'acc-summary',
    label: 'Resumen de Administración',
    icon: Landmark,
    group: 'Administración',
    type: 'navigate',
    href: (s) => `/${s}/administracion`,
    keywords: ['plata', 'cuentas', 'contadora', ...ACC_KEYWORDS],
    roles: ['owner', 'accountant'],
    accounting: 'read_or_setup',
  },
  {
    id: 'acc-suppliers',
    label: 'Proveedores',
    icon: Truck,
    group: 'Administración',
    type: 'navigate',
    href: (s) => `/${s}/administracion/compras?tab=proveedores`,
    keywords: ['compras', 'deudas', 'cuenta corriente', 'saldo', ...ACC_KEYWORDS],
    roles: ['owner', 'accountant'],
    accounting: 'read',
  },
  {
    id: 'acc-customers',
    label: 'Clientes y plataformas',
    icon: HandCoins,
    group: 'Administración',
    type: 'navigate',
    href: (s) => `/${s}/administracion/ventas?tab=clientes`,
    keywords: ['ventas', 'tarjetas', 'posnet', 'pedidosya', 'cobros', 'te deben', ...ACC_KEYWORDS],
    roles: ['owner', 'accountant'],
    accounting: 'read',
  },
  {
    id: 'acc-treasury',
    label: 'Cajas y bancos',
    icon: Wallet,
    group: 'Administración',
    type: 'navigate',
    href: (s) => `/${s}/administracion/cajas`,
    keywords: ['caja', 'banco', 'mercado pago', 'efectivo', 'saldo', 'flujo', ...ACC_KEYWORDS],
    roles: ['owner', 'accountant'],
    accounting: 'read',
  },
  {
    id: 'acc-journal',
    label: 'Libro diario',
    icon: BookText,
    group: 'Administración',
    type: 'navigate',
    href: (s) => `/${s}/administracion/libros/diario`,
    keywords: ['diario', 'asientos', 'libro', ...ACC_KEYWORDS],
    roles: ['owner', 'accountant'],
    accounting: 'read',
  },
  {
    id: 'acc-ledger',
    label: 'Mayor',
    icon: BookText,
    group: 'Administración',
    type: 'navigate',
    href: (s) => `/${s}/administracion/libros/mayor`,
    keywords: ['mayor', 'cuenta', 'libro', ...ACC_KEYWORDS],
    roles: ['owner', 'accountant'],
    accounting: 'read',
  },
  {
    id: 'acc-trial-balance',
    label: 'Sumas y saldos',
    icon: Scale,
    group: 'Administración',
    type: 'navigate',
    href: (s) => `/${s}/administracion/libros/sumas-y-saldos`,
    keywords: ['balance', 'sumas', 'saldos', 'balancete', ...ACC_KEYWORDS],
    roles: ['owner', 'accountant'],
    accounting: 'read',
  },
  {
    id: 'acc-vat-purchases',
    label: 'Libro IVA compras',
    icon: ReceiptText,
    group: 'Administración',
    type: 'navigate',
    href: (s) => `/${s}/administracion/libros/iva-compras`,
    keywords: ['iva', 'compras', 'credito fiscal', 'crédito fiscal', 'libro', ...ACC_KEYWORDS],
    roles: ['owner', 'accountant'],
    accounting: 'read',
  },
  {
    id: 'acc-vat-sales',
    label: 'Libro IVA ventas',
    icon: ReceiptText,
    group: 'Administración',
    type: 'navigate',
    href: (s) => `/${s}/administracion/libros/iva-ventas`,
    keywords: ['iva', 'ventas', 'debito fiscal', 'débito fiscal', 'libro', ...ACC_KEYWORDS],
    roles: ['owner', 'accountant'],
    accounting: 'read',
  },
  {
    id: 'acc-vat-position',
    label: 'Posición de IVA',
    icon: Scale,
    group: 'Administración',
    type: 'navigate',
    href: (s) => `/${s}/administracion/libros/posicion-iva`,
    keywords: [
      'iva',
      'posicion',
      'a pagar',
      'saldo tecnico',
      'saldo técnico',
      'arca',
      'afip',
      ...ACC_KEYWORDS,
    ],
    roles: ['owner', 'accountant'],
    accounting: 'read',
  },
  {
    id: 'acc-month-pack',
    label: 'Paquete del mes',
    icon: BookOpen,
    group: 'Administración',
    type: 'navigate',
    href: (s) => `/${s}/administracion/libros`,
    keywords: ['libros', 'exportar', 'contadora', 'mes', 'csv', ...ACC_KEYWORDS],
    roles: ['owner', 'accountant'],
    accounting: 'read',
  },
  {
    id: 'acc-month-closes',
    label: 'Cierres de mes',
    icon: CalendarCheck,
    group: 'Administración',
    type: 'navigate',
    href: (s) => `/${s}/administracion/libros/cierres`,
    keywords: ['cierre', 'mes', 'ejercicio', 'periodos', 'períodos', ...ACC_KEYWORDS],
    roles: ['owner', 'accountant'],
    accounting: 'read',
  },
  {
    id: 'acc-chart',
    label: 'Plan de cuentas',
    icon: ListTree,
    group: 'Administración',
    type: 'navigate',
    href: (s) => `/${s}/administracion/plan-de-cuentas`,
    keywords: ['cuentas', 'plan', 'codigo', 'código', 'imputacion', 'imputación', ...ACC_KEYWORDS],
    roles: ['owner', 'accountant'],
    accounting: 'read',
  },
  {
    id: 'acc-import',
    label: 'Importar de ARCA, Mercado Pago o el banco',
    icon: FileDown,
    group: 'Administración',
    type: 'navigate',
    href: (s) => `/${s}/administracion/importar`,
    keywords: [
      'importar',
      'subir',
      'archivo',
      'arca',
      'afip',
      'mis comprobantes',
      'compras',
      'mercado pago',
      'liquidaciones',
      'banco',
      'extracto',
      'csv',
      'zip',
      ...ACC_KEYWORDS,
    ],
    roles: ['owner', 'accountant'],
    accounting: 'read',
  },
  {
    id: 'acc-connect-arca',
    label: 'Conectar ARCA',
    icon: PlugZap,
    group: 'Administración',
    type: 'navigate',
    href: (s) => `/${s}/administracion/ajustes/arca`,
    keywords: [
      'arca',
      'afip',
      'certificado',
      'clave fiscal',
      'factura electronica',
      'factura electrónica',
      'cae',
      'padron',
      'padrón',
      ...ACC_KEYWORDS,
    ],
    accounting: 'write',
  },
  {
    id: 'acc-getting-started',
    label: 'Cómo arrancar con Administración',
    icon: MapIcon,
    group: 'Administración',
    type: 'navigate',
    href: (s) => `/${s}/administracion/guias/como-arrancar`,
    keywords: [
      'guia',
      'guía',
      'empezar',
      'arrancar',
      'primeros pasos',
      'ayuda',
      'que cargo',
      'qué cargo',
      ...ACC_KEYWORDS,
    ],
    roles: ['owner', 'accountant'],
    accounting: 'read',
  },
  {
    id: 'acc-guides',
    label: 'Guías de Administración',
    icon: BookOpen,
    group: 'Administración',
    type: 'navigate',
    href: (s) => `/${s}/administracion/guias`,
    keywords: [
      'guias',
      'guías',
      'instructivo',
      'paso a paso',
      'como bajo',
      'cómo bajo',
      'mis comprobantes',
      'ayuda',
      ...ACC_KEYWORDS,
    ],
    roles: ['owner', 'accountant'],
    accounting: 'read',
  },
  {
    id: 'acc-settings',
    label: 'Ajustes de Administración',
    icon: Settings2,
    group: 'Administración',
    type: 'navigate',
    href: (s) => `/${s}/administracion/ajustes`,
    keywords: [
      'accesos',
      'cajas',
      'medios de pago',
      'puntos de venta',
      'sas',
      'cuit',
      ...ACC_KEYWORDS,
    ],
    accounting: 'write',
  },
]

export const commandEntries: CommandEntry[] = [
  // Acciones rápidas (mutaciones / new resource)
  {
    id: 'new-customer',
    label: 'Nuevo cliente',
    icon: Users,
    group: 'Acciones rápidas',
    type: 'navigate-new',
    href: (s) => `/${s}/clientes/nuevo`,
    keywords: ['cliente', 'persona', 'agregar', 'crear'],
  },
  {
    // El alta pelada: al guardar vuelve a la lista de Reservas en el día de la
    // reserva (sin ?volver, el destino por defecto).
    id: 'new-reservation',
    label: 'Nueva reserva',
    icon: CalendarCheck,
    group: 'Acciones rápidas',
    type: 'navigate-new',
    href: (s) => `/${s}/reservas/nuevo`,
    keywords: ['reserva', 'mesa', 'agendar', 'crear'],
    roles: ['owner', 'host'],
  },
  {
    id: 'new-broadcast',
    label: 'Nueva difusión',
    icon: Megaphone,
    group: 'Acciones rápidas',
    type: 'navigate-new',
    href: (s) => `/${s}/mensajeria/difusiones/nueva`,
    keywords: ['enviar', 'whatsapp', 'broadcast', 'campaña'],
  },
  {
    id: 'new-event',
    label: 'Programar evento',
    icon: CalendarDays,
    group: 'Acciones rápidas',
    type: 'navigate-new',
    href: (s) => `/${s}/eventos/programados/nuevo`,
    keywords: ['fecha', 'agenda', 'show', 'fiesta', 'calendario'],
    roles: ['owner', 'host'],
  },
  {
    id: 'new-flow',
    label: 'Nueva automatización',
    icon: Workflow,
    group: 'Acciones rápidas',
    type: 'navigate-new',
    href: (s) => `/${s}/mensajeria/flows/nuevo`,
    keywords: ['automatización', 'recurrente'],
  },
  {
    id: 'new-marketing-task',
    label: 'Nueva tarea de marketing',
    icon: ListChecks,
    group: 'Acciones rápidas',
    type: 'navigate-new',
    href: (s) => `/${s}/tareas`,
    keywords: ['tarea', 'marketing', 'contenido', 'reel', 'historia', 'diseño'],
  },
  {
    id: 'new-landing-page',
    label: 'Nueva página HTML',
    icon: FileCode2,
    group: 'Acciones rápidas',
    type: 'navigate-new',
    href: (s) => `/${s}/paginas`,
    // «promo» al final: antes de «evento» armaba un falso parecido con «importar» y esta
    // acción quedaba primera (y elegida) al buscar los importadores de Administración.
    keywords: ['landing', 'html', 'evento', 'pagina', 'publicar', 'promo'],
  },
  {
    id: 'close-table-legacy',
    label: 'Cerrar mesa (legacy)',
    icon: Receipt,
    group: 'Acciones rápidas',
    type: 'navigate',
    href: (s) => `/${s}/visitas/nueva`,
    keywords: ['cerrar', 'mesa', 'cobrar'],
    feature: 'table_service',
  },

  // Operación (turno en vivo)
  {
    id: 'live-sessions',
    label: 'Salón en vivo',
    icon: ClipboardList,
    group: 'Operación',
    type: 'navigate',
    href: (s) => `/${s}/salon/mesas`,
    keywords: ['mesas', 'sesiones', 'salón', 'live'],
    feature: 'table_service',
  },
  {
    id: 'kitchen',
    label: 'Cocina',
    icon: ChefHat,
    group: 'Operación',
    type: 'navigate',
    href: (s) => `/${s}/salon/cocina`,
    keywords: ['kitchen', 'tickets', 'pedidos'],
    feature: 'kitchen',
  },
  {
    id: 'inbox',
    label: 'Inbox',
    icon: Inbox,
    group: 'Operación',
    type: 'navigate',
    href: (s) => `/${s}/mensajeria/inbox`,
    keywords: ['mensajes', 'whatsapp', 'instagram', 'inbox', 'bandeja', 'mensajeria'],
  },

  // Ir a (navegación)
  {
    id: 'operativo',
    label: 'Operativo',
    icon: ClipboardList,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/operativo`,
    keywords: ['hoy', 'timeline', 'llegadas', 'dia'],
    roles: ['owner', 'host'],
  },
  {
    id: 'my-numbers',
    label: 'Mis números',
    icon: BarChart3,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/mis-numeros`,
    keywords: ['comisiones', 'ganancias', 'plata', 'liquidacion'],
    roles: ['host'],
  },
  {
    id: 'home',
    label: 'Resumen',
    icon: LayoutDashboard,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}`,
    keywords: ['dashboard', 'home', 'inicio'],
  },
  {
    id: 'people',
    label: 'Personas',
    icon: Users,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/clientes`,
    keywords: ['clientes', 'crm'],
  },
  {
    // Desde el 07/10/2026 son pestañas de Clientes, no ítems del menú lateral.
    id: 'accredit',
    label: 'Acreditar puntos',
    icon: ScanLine,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/acreditar`,
    keywords: ['acreditar', 'puntos', 'club', 'cliente', 'sumar'],
  },
  {
    id: 'club-qr',
    label: 'QR del club',
    icon: QrCode,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/local/captura`,
    keywords: ['qr', 'club', 'carta', 'imprimir', 'mesa'],
  },
  {
    // Pestaña de Estadísticas (antes, ítem del menú).
    id: 'reviews',
    label: 'Reseñas',
    icon: MessageSquareText,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/reviews`,
    keywords: ['reseñas', 'resenas', 'google', 'opiniones', 'estrellas'],
    feature: 'reviews',
  },
  {
    id: 'marketing-tasks',
    label: 'Tareas de marketing',
    icon: ListChecks,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/tareas`,
    keywords: ['tareas', 'marketing', 'contenido', 'organico', 'checklist', 'socios'],
  },
  {
    id: 'public-links',
    label: 'Link de Instagram',
    icon: Link2,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/enlaces`,
    keywords: ['bio', 'instagram', 'linktree', 'biolink', 'enlaces', 'links'],
  },
  {
    id: 'landing-pages',
    label: 'Páginas',
    icon: FileCode2,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/paginas`,
    keywords: ['landing', 'html', 'pagina', 'promo', 'evento', 'link', 'web'],
  },
  {
    id: 'audiences',
    label: 'Audiencias',
    icon: UsersRound,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/mensajeria/audiencias`,
    keywords: ['segmentos', 'filtros'],
  },
  {
    id: 'broadcasts',
    label: 'Difusiones',
    icon: Megaphone,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/mensajeria/difusiones`,
    keywords: ['campañas', 'whatsapp'],
  },
  {
    id: 'flows',
    label: 'Automatizaciones',
    icon: Workflow,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/mensajeria/flows`,
    keywords: ['automatización'],
  },
  {
    id: 'calendar',
    label: 'Calendario',
    icon: CalendarDays,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/eventos/programados`,
    // Desde el calendario también se reserva (por servicio o adentro de un
    // evento): buscar «reserva» trae Reservas y también el calendario.
    keywords: [
      'agenda',
      'mes',
      'sushi libre',
      'pizza libre',
      'cupos',
      'eventos',
      'fiesta',
      'show',
      'peña',
      'reserva',
      'reservas',
      'reservar',
      'mesa',
    ],
    roles: ['owner', 'host'],
  },
  {
    id: 'reservations',
    label: 'Reservas',
    icon: CalendarCheck,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/reservas`,
    keywords: ['reserva', 'mesa', 'reservar', 'lista', 'pasar lista'],
    roles: ['owner', 'host'],
  },
  {
    id: 'menu',
    label: 'Carta',
    icon: UtensilsCrossed,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/menu`,
    keywords: ['menu', 'carta', 'productos', 'items', 'fotos'],
    roles: ['owner', 'editor'],
  },
  {
    id: 'club',
    label: 'Club de beneficios',
    icon: Star,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/club?tab=programa`,
    keywords: ['fidelizacion', 'lealtad', 'loyalty', 'beneficios'],
  },
  {
    id: 'tiers',
    label: 'Niveles del club',
    icon: Sparkles,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/club?tab=programa`,
    keywords: ['vip', 'tiers', 'escalones', 'club'],
  },
  {
    id: 'points',
    label: 'Puntos y recompensas',
    icon: Gift,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/club?tab=programa`,
    keywords: ['fidelidad', 'rewards', 'recompensas', 'club'],
  },
  {
    id: 'punch-cards',
    label: 'Punch cards',
    icon: Stamp,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/club?tab=punch`,
    keywords: ['tarjetas', 'sellos', 'club'],
  },
  {
    id: 'welcome-gift',
    label: 'Regalo de bienvenida',
    icon: Star,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/club?tab=bienvenida`,
    keywords: ['bienvenida', 'welcome', 'regalo', 'club'],
  },
  {
    id: 'tags',
    label: 'Tags de carta',
    icon: Tags,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/menu/tags`,
    keywords: ['etiquetas'],
    roles: ['owner', 'editor'],
  },
  {
    id: 'floor-plan',
    label: 'Plano del salón',
    icon: LayoutGrid,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/local/mesas`,
    keywords: ['mesas', 'floor', 'plano', 'salón'],
    feature: 'floor_plan',
  },
  {
    id: 'auto-accept',
    label: 'Auto-aceptación',
    icon: Zap,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/local/auto-aceptacion`,
    keywords: ['settings'],
    feature: 'auto_accept',
  },
  {
    id: 'templates',
    label: 'Plantillas WhatsApp',
    icon: MessageSquareText,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/mensajeria/plantillas`,
    keywords: ['mensajes', 'plantillas'],
  },
  {
    id: 'team',
    label: 'Equipo',
    icon: UsersRound,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/configuracion/equipo`,
    keywords: ['staff', 'invitar'],
  },
  {
    id: 'stats',
    label: 'Estadísticas',
    icon: BarChart3,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/estadisticas`,
    keywords: ['reportes', 'analytics'],
  },
  {
    id: 'how-it-went',
    label: 'Cómo nos fue',
    icon: PartyPopper,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/estadisticas/como-nos-fue`,
    keywords: [
      'gente',
      'personas',
      'cubiertos',
      'asistencia',
      'evento',
      'noche',
      'promedio',
      'como nos fue',
      'pauta',
      'meta',
      'anuncios',
      'publicidad',
    ],
  },
  {
    id: 'deposits',
    label: 'Señas',
    icon: Banknote,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/estadisticas/senas`,
    // Con y sin tilde: el matching de cmdk es literal sobre label + keywords y
    // nadie escribe "señas" con la eñe cuando está apurado.
    keywords: ['senas', 'senias', 'sena', 'adelanto', 'anticipo', 'deposito', 'plata', 'ingresos'],
  },
  {
    id: 'commissions',
    label: 'Comisiones',
    icon: Coins,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/estadisticas/comisiones`,
    keywords: ['liquidacion', 'gestores', 'plata'],
  },
  {
    id: 'docs',
    label: 'Documentación',
    icon: BookOpen,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/docs`,
    keywords: ['ayuda', 'guía', 'manual', 'help'],
  },
  {
    id: 'settings',
    label: 'Configuración',
    icon: Settings2,
    group: 'Ir a',
    type: 'navigate',
    href: (s) => `/${s}/configuracion`,
    keywords: ['ajustes', 'preferencias'],
  },

  // Administración (H.0)
  ...accountingEntries,
]
