-- Parte 2 de 4 de la migración #16 (acc_chart_flex): plan de cuentas estándar nuevo.
-- Inspirado en el modelo de la contadora (5 niveles: 1.0.00.00.000 grupos … 1.1.01.01.001 imputables;
-- 1 Activo, 2 Pasivo, 3 Patrimonio neto, 4 Resultado del ejercicio con 4.1 Ingresos y 4.2 Egresos adentro,
-- 5 Compras) y adaptado a una SAS gastronómica responsable inscripta de Córdoba. Donde el modelo tiene el
-- mismo concepto se usa su código (IVA crédito fiscal 1.1.03.04.028, Proveedores 2.1.01.01.001…).
-- Conserva TODAS las system_key del plan anterior con el mismo tipo, lado normal, control
-- (requires_party), «¿En qué?» (purchase_selectable) y regularizadoras: el motor depende de eso.
-- 226 cuentas: 73 grupos y 153 imputables (88 con system_key, 19 de control, 51 de «¿En qué?»).
-- Solo lo usan las puestas en marcha nuevas (ningún bar está configurado todavía). Idempotente por
-- (tenant_id, code); inserta por profundidad del código y la madre sale del código (acc_code_parent):
-- los códigos de «Caja y bancos» (1.1.01.01.001, .002…) y de las tarjetas de la empresa los pone el
-- asistente con acc_next_child_code.
-- El bloque entre los marcadores @acc-seed-chart lo parsea accounting-system-keys.test.ts (toma la última
-- migración que lo tiene): una fila por línea, columnas (code, name, type, normal_side, postable,
-- system_key, requires_party, purchase_selectable, description). Es exactamente STANDARD_CHART de
-- lib/accounting/chart.ts.
create or replace function private.acc_seed_chart(p_tenant uuid)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_level int;
  v_n int;
  v_total int := 0;
begin
  if p_tenant is null or not exists (select 1 from public.tenants t where t.id = p_tenant) then
    raise exception 'forbidden' using errcode = '42501';
  end if;
  -- Por profundidad: cada hija encuentra a su madre ya insertada.
  for v_level in 1..5 loop
    insert into public.acc_accounts (tenant_id, code, name, type, normal_side, parent_id, postable, system_key,
                                     requires_party, purchase_selectable, manual_selectable, description)
    select p_tenant, c.code, c.name, c.type::public.acc_account_type, c.normal_side::public.acc_side,
           case when v_level = 1 then null
                else (select pa.id from public.acc_accounts pa
                       where pa.tenant_id = p_tenant and pa.code = private.acc_code_parent(c.code)) end,
           c.postable, c.system_key, c.requires_party, c.purchase_selectable, true, c.description
      from (values
        -- @acc-seed-chart:begin (code, name, type, normal_side, postable, system_key, requires_party, purchase_selectable, description)
        ('1.0.00.00.000', 'ACTIVO', 'asset', 'debit', false, null, false, false, null),
        ('1.1.00.00.000', 'Activo corriente', 'asset', 'debit', false, null, false, false, null),
        ('1.1.01.00.000', 'Caja, bancos y valores a depositar', 'asset', 'debit', false, null, false, false, null),
        ('1.1.01.01.000', 'Caja y bancos', 'asset', 'debit', false, null, false, false, 'Cada caja, cuenta bancaria y billetera tiene acá su cuenta (las crea el asistente: Caja .001, Mercado Pago .002, banco .003…)'),
        ('1.1.01.03.000', 'Valores', 'asset', 'debit', false, null, false, false, null),
        ('1.1.01.03.001', 'Valores a depositar', 'asset', 'debit', true, null, false, false, 'Cheques recibidos que todavía no depositaste'),
        ('1.1.01.04.000', 'Fondos fijos y moneda extranjera', 'asset', 'debit', false, null, false, false, null),
        ('1.1.01.04.001', 'Fondos a rendir', 'asset', 'debit', true, null, false, false, 'Plata entregada a alguien que después rinde con comprobantes'),
        ('1.1.01.04.002', 'Moneda extranjera', 'asset', 'debit', true, null, false, false, 'Dólares u otra moneda de la SAS, valuados en pesos (los carga la contadora)'),
        ('1.1.02.00.000', 'Inversiones corrientes', 'asset', 'debit', false, null, false, false, null),
        ('1.1.02.01.000', 'Depósitos a plazo fijo', 'asset', 'debit', false, null, false, false, null),
        ('1.1.02.01.001', 'Plazos fijos en pesos', 'asset', 'debit', true, null, false, false, 'Plazos fijos a menos de un año'),
        ('1.1.02.01.002', 'Plazos fijos en dólares', 'asset', 'debit', true, null, false, false, 'Plazos fijos en moneda extranjera, valuados en pesos'),
        ('1.1.03.00.000', 'Créditos', 'asset', 'debit', false, null, false, false, null),
        ('1.1.03.01.000', 'Créditos por ventas', 'asset', 'debit', false, null, false, false, null),
        ('1.1.03.01.001', 'Deudores por ventas', 'asset', 'debit', true, 'receivable_customers', true, false, 'Lo que te deben empresas y clientes con cuenta corriente'),
        ('1.1.03.01.003', 'Tarjetas de crédito a cobrar', 'asset', 'debit', true, 'receivable_credit_cards', true, false, 'Ventas con crédito que el procesador todavía no acreditó'),
        ('1.1.03.01.004', 'Tarjetas de débito a cobrar', 'asset', 'debit', true, 'receivable_debit_cards', true, false, 'Ventas con débito que el procesador todavía no acreditó'),
        ('1.1.03.01.005', 'Mercado Pago a acreditar', 'asset', 'debit', true, 'receivable_wallets', true, false, 'QR y transferencias vendidos que todavía no registraste como acreditados («Ajustar saldo» de Mercado Pago)'),
        ('1.1.03.01.006', 'Plataformas de delivery a cobrar', 'asset', 'debit', true, 'receivable_platforms', true, false, 'Lo que te deben PedidosYa, Rappi y las demás; si una liquidación da negativo, acá queda lo que les debés'),
        ('1.1.03.01.009', 'Previsión para deudores incobrables (regularizadora)', 'asset', 'credit', true, 'bad_debt_allowance', false, false, 'Ajuste de la contadora por cobros dudosos'),
        ('1.1.03.02.000', 'Otros créditos', 'asset', 'debit', false, null, false, false, null),
        ('1.1.03.02.001', 'Gastos pagados por adelantado', 'asset', 'debit', true, 'prepaid_expenses', false, true, 'Seguros o alquileres pagados por varios meses'),
        ('1.1.03.02.002', 'Diferencias de cobro a conciliar', 'asset', 'debit', true, 'reconciliation_differences', false, false, 'Lo que no se explica al ajustar el saldo de Mercado Pago o de un banco; la contadora lo reclasifica'),
        ('1.1.03.02.004', 'Deudores varios', 'asset', 'debit', true, null, false, false, 'Otros que le deben plata a la SAS (no por ventas)'),
        ('1.1.03.02.005', 'Anticipos y préstamos al personal', 'asset', 'debit', true, null, false, false, 'Adelantos de sueldo o préstamos a empleados'),
        ('1.1.03.02.010', 'Anticipos a proveedores', 'asset', 'debit', true, 'supplier_advances', false, false, 'La contadora reclasifica acá los pagos a cuenta al cierre del ejercicio'),
        ('1.1.03.04.000', 'Anticipos de impuestos y créditos fiscales', 'asset', 'debit', false, null, false, false, null),
        ('1.1.03.04.003', 'Anticipos de Ganancias', 'asset', 'debit', true, 'income_tax_advances', false, false, 'Anticipos de Ganancias pagados'),
        ('1.1.03.04.006', 'Retenciones de Ganancias sufridas', 'asset', 'debit', true, 'income_tax_withholdings', false, false, 'Ganancias que te retienen al cobrar, con certificado'),
        ('1.1.03.04.008', 'Retenciones y percepciones municipales sufridas', 'asset', 'debit', true, null, false, false, 'Comercio e Industria que te retienen o perciben; se descuenta de la contribución del mes'),
        ('1.1.03.04.011', 'Saldo a favor de Ganancias', 'asset', 'debit', true, null, false, false, 'Lo que sobró de la declaración jurada de Ganancias'),
        ('1.1.03.04.013', 'IVA saldo técnico a favor', 'asset', 'debit', true, 'vat_technical_balance', false, false, 'Cuando en un mes compraste más IVA del que vendiste; se usa en los meses siguientes'),
        ('1.1.03.04.014', 'Retenciones de IIBB sufridas (tarjetas y plataformas)', 'asset', 'debit', true, 'iibb_withholdings', false, false, 'Ingresos Brutos que te retienen al acreditar tarjetas, plataformas o clientes'),
        ('1.1.03.04.016', 'Retenciones de seguridad social (SUSS) sufridas', 'asset', 'debit', true, null, false, false, 'Aportes que te retiene un cliente al pagarte, con certificado'),
        ('1.1.03.04.022', 'IIBB Córdoba saldo a favor', 'asset', 'debit', true, 'iibb_balance', false, false, 'Lo que sobró de la declaración de Ingresos Brutos (Rentas Córdoba)'),
        ('1.1.03.04.026', 'Impuesto ley 25.413 computable en Ganancias', 'asset', 'debit', true, 'bank_tax_credit', false, false, 'La parte del impuesto al cheque que se descuenta de Ganancias (33 % por defecto)'),
        ('1.1.03.04.028', 'IVA crédito fiscal', 'asset', 'debit', true, 'vat_credit', false, false, 'El IVA de las facturas A que te hacen los responsables inscriptos: se descuenta del IVA que cobrás'),
        ('1.1.03.04.029', 'Retenciones de IVA sufridas', 'asset', 'debit', true, 'vat_withholdings', false, false, 'IVA que te retuvo un cliente o un procesador al pagarte, con certificado'),
        ('1.1.03.04.030', 'Percepciones de IIBB sufridas', 'asset', 'debit', true, 'iibb_perceptions', false, false, 'Ingresos Brutos que te cobró un proveedor en la factura'),
        ('1.1.03.04.031', 'IVA crédito fiscal a documentar', 'asset', 'debit', true, 'vat_credit_pending', true, false, 'IVA de comisiones ya descontadas (Mercado Pago, plataformas) cuya factura mensual todavía no llegó'),
        ('1.1.03.04.032', 'IVA saldo de libre disponibilidad', 'asset', 'debit', true, 'vat_free_balance', false, false, 'Percepciones y retenciones de IVA que sobraron; sirven para pagar IVA u otros impuestos'),
        ('1.1.03.04.033', 'Percepciones de IVA sufridas', 'asset', 'debit', true, 'vat_perceptions', false, false, 'IVA extra que te cobró un proveedor en la factura; se descuenta en la liquidación del mes'),
        ('1.1.03.04.034', 'Recaudaciones IIBB SIRCREB (bancos)', 'asset', 'debit', true, 'iibb_sircreb', false, false, 'Lo que el banco descuenta de Ingresos Brutos sobre los créditos de la cuenta'),
        ('1.1.03.04.035', 'Recaudaciones IIBB SIRCUPA (billeteras)', 'asset', 'debit', true, 'iibb_sircupa', false, false, 'Lo que Mercado Pago descuenta de Ingresos Brutos sobre lo que entra'),
        ('1.1.03.04.036', 'Percepciones de Ganancias sufridas', 'asset', 'debit', true, 'income_tax_perceptions', false, false, 'Ganancias que te cobra un proveedor en la factura'),
        ('1.1.04.00.000', 'Bienes de cambio', 'asset', 'debit', false, null, false, false, null),
        ('1.1.04.01.000', 'Mercaderías (existencia)', 'asset', 'debit', true, 'inventory', false, false, 'Existencia al cierre (la carga la contadora hasta el Sprint de Stock)'),
        ('1.2.00.00.000', 'Activo no corriente', 'asset', 'debit', false, null, false, false, null),
        ('1.2.02.00.000', 'Bienes de uso', 'asset', 'debit', false, null, false, false, null),
        ('1.2.02.01.000', 'Equipamiento de cocina y barra', 'asset', 'debit', false, null, false, false, null),
        ('1.2.02.01.001', 'Equipamiento de cocina y barra', 'asset', 'debit', true, null, false, true, 'Hornos, heladeras, cafeteras, freidoras'),
        ('1.2.02.01.002', 'Amortización acumulada de equipamiento (regularizadora)', 'asset', 'credit', true, null, false, false, 'La carga la contadora al cierre'),
        ('1.2.02.03.000', 'Rodados', 'asset', 'debit', false, null, false, false, null),
        ('1.2.02.03.001', 'Rodados', 'asset', 'debit', true, null, false, true, 'Vehículos de la SAS (motos de delivery, utilitarios)'),
        ('1.2.02.03.003', 'Amortización acumulada de rodados (regularizadora)', 'asset', 'credit', true, null, false, false, 'La carga la contadora al cierre'),
        ('1.2.02.04.000', 'Muebles y útiles', 'asset', 'debit', false, null, false, false, null),
        ('1.2.02.04.001', 'Muebles y útiles', 'asset', 'debit', true, null, false, true, 'Mesas, sillas, barra y estanterías que duran años'),
        ('1.2.02.04.002', 'Amortización acumulada de muebles y útiles (regularizadora)', 'asset', 'credit', true, null, false, false, 'La carga la contadora al cierre'),
        ('1.2.02.05.000', 'Instalaciones', 'asset', 'debit', false, null, false, false, null),
        ('1.2.02.05.001', 'Instalaciones', 'asset', 'debit', true, null, false, true, 'Obras e instalaciones del local: eléctrica, gas, aire acondicionado'),
        ('1.2.02.05.002', 'Amortización acumulada de instalaciones (regularizadora)', 'asset', 'credit', true, null, false, false, 'La carga la contadora al cierre'),
        ('1.2.02.07.000', 'Vajilla', 'asset', 'debit', false, null, false, false, null),
        ('1.2.02.07.001', 'Vajilla, cristalería y cubiertos', 'asset', 'debit', true, null, false, true, 'Platos, copas y cubiertos de la compra inicial o de una renovación grande'),
        ('1.2.02.07.002', 'Amortización acumulada de vajilla (regularizadora)', 'asset', 'credit', true, null, false, false, 'La carga la contadora al cierre'),
        ('1.2.02.09.000', 'Mejoras en inmuebles de terceros', 'asset', 'debit', false, null, false, false, null),
        ('1.2.02.09.001', 'Mejoras en inmuebles de terceros', 'asset', 'debit', true, null, false, true, 'Reformas en el local alquilado'),
        ('1.2.02.09.002', 'Amortización acumulada de mejoras (regularizadora)', 'asset', 'credit', true, null, false, false, 'La carga la contadora al cierre'),
        ('1.2.02.10.000', 'Equipos de computación', 'asset', 'debit', false, null, false, false, null),
        ('1.2.02.10.001', 'Equipos de computación', 'asset', 'debit', true, null, false, true, 'Computadoras, tablets, impresoras y comanderas'),
        ('1.2.02.10.002', 'Amortización acumulada de computación (regularizadora)', 'asset', 'credit', true, null, false, false, 'La carga la contadora al cierre'),
        ('1.2.02.99.000', 'Amortización acumulada general', 'asset', 'debit', false, null, false, false, null),
        ('1.2.02.99.001', 'Amortización acumulada de bienes de uso (regularizadora)', 'asset', 'credit', true, 'accumulated_depreciation', false, false, 'La regularizadora general del sistema; la contadora puede usar la de cada rubro'),
        ('1.2.03.00.000', 'Activos intangibles', 'asset', 'debit', false, null, false, false, null),
        ('1.2.03.01.000', 'Intangibles', 'asset', 'debit', false, null, false, false, null),
        ('1.2.03.01.001', 'Software y licencias', 'asset', 'debit', true, null, false, true, 'Licencias que duran más de un año'),
        ('1.2.03.01.002', 'Gastos de organización', 'asset', 'debit', true, null, false, true, 'Gastos de constitución de la SAS'),
        ('1.2.03.01.009', 'Amortización acumulada de intangibles (regularizadora)', 'asset', 'credit', true, null, false, false, 'La carga la contadora al cierre'),
        ('1.2.04.00.000', 'Otros activos no corrientes', 'asset', 'debit', false, null, false, false, null),
        ('1.2.04.01.000', 'Depósitos y garantías', 'asset', 'debit', false, null, false, false, null),
        ('1.2.04.01.001', 'Depósitos en garantía', 'asset', 'debit', true, null, false, false, 'Lo que dejaste de garantía al alquilar el local'),
        ('2.0.00.00.000', 'PASIVO', 'liability', 'credit', false, null, false, false, null),
        ('2.1.00.00.000', 'Pasivo corriente', 'liability', 'credit', false, null, false, false, null),
        ('2.1.01.00.000', 'Deudas', 'liability', 'credit', false, null, false, false, null),
        ('2.1.01.01.000', 'Deudas comerciales', 'liability', 'credit', false, null, false, false, 'Proveedores y señas; acá se crean también las tarjetas de crédito de la empresa'),
        ('2.1.01.01.001', 'Proveedores', 'liability', 'credit', true, 'payable_suppliers', true, false, 'Lo que les debés a los proveedores, factura por factura'),
        ('2.1.01.01.003', 'Anticipos de clientes (señas)', 'liability', 'credit', true, 'customer_deposits', true, false, 'Señas y anticipos cobrados antes de la venta'),
        ('2.1.01.03.000', 'Deudas fiscales', 'liability', 'credit', false, null, false, false, null),
        ('2.1.01.03.001', 'IVA a pagar', 'liability', 'credit', true, 'vat_payable', true, false, 'Lo que da la liquidación mensual del IVA, hasta que se paga'),
        ('2.1.01.03.002', 'Comercio e Industria a pagar', 'liability', 'credit', true, 'municipal_payable', true, false, 'La contribución municipal sobre comercio e industria, hasta que se paga'),
        ('2.1.01.03.003', 'IIBB Córdoba a pagar', 'liability', 'credit', true, 'iibb_payable', true, false, 'La declaración de Ingresos Brutos del mes (Rentas Córdoba), hasta que se paga'),
        ('2.1.01.03.011', 'Ganancias a pagar', 'liability', 'credit', true, 'income_tax_payable', true, false, 'Declaración y anticipos de Ganancias'),
        ('2.1.01.03.015', 'IVA débito fiscal', 'liability', 'credit', true, 'vat_debit', false, false, 'El IVA de lo que facturaste'),
        ('2.1.01.03.018', 'Otros impuestos y planes de pago a pagar', 'liability', 'credit', true, 'other_taxes_payable', true, false, 'Planes de pago de ARCA y otros tributos'),
        ('2.1.01.04.000', 'Deudas sociales', 'liability', 'credit', false, null, false, false, null),
        ('2.1.01.04.001', 'Sueldos a pagar', 'liability', 'credit', true, 'payroll_payable', true, false, 'Sueldos netos liquidados que todavía no se pagaron'),
        ('2.1.01.04.002', 'Honorarios a pagar', 'liability', 'credit', true, null, false, false, 'Honorarios de profesionales ya devengados que todavía no se pagaron'),
        ('2.1.01.04.003', 'Provisión SAC y vacaciones', 'liability', 'credit', true, 'payroll_provisions', false, false, 'La carga la contadora'),
        ('2.1.01.05.000', 'Aportes y contribuciones', 'liability', 'credit', false, null, false, false, null),
        ('2.1.01.05.001', 'Cargas sociales a pagar (F.931)', 'liability', 'credit', true, 'social_security_payable', true, false, 'Aportes y contribuciones del F.931'),
        ('2.1.01.05.002', 'ART a pagar', 'liability', 'credit', true, null, false, false, 'La cuota de la aseguradora de riesgos del trabajo, hasta que se paga'),
        ('2.1.01.05.003', 'Sindicato y obra social a pagar', 'liability', 'credit', true, 'union_payable', true, false, 'Cuotas sindicales y de obra social retenidas'),
        ('2.1.01.05.005', 'Fondo convenio a pagar', 'liability', 'credit', true, null, false, false, 'Aportes del convenio colectivo gastronómico retenidos o a cargo de la SAS'),
        ('2.1.01.06.000', 'Otras deudas', 'liability', 'credit', false, null, false, false, null),
        ('2.1.01.06.003', 'Acreedores varios', 'liability', 'credit', true, 'other_payables', true, false, 'Otras deudas con un acreedor identificado'),
        ('2.1.01.06.007', 'Cuentas particulares de socios', 'liability', 'credit', true, 'partners_current', true, false, 'Retiros y aportes de cada socio'),
        ('2.1.01.07.000', 'Deudas financieras', 'liability', 'credit', false, null, false, false, null),
        ('2.1.01.07.001', 'Préstamos bancarios', 'liability', 'credit', true, 'bank_loans', false, false, 'Préstamos del banco a menos de un año'),
        ('2.1.01.07.002', 'Préstamos de socios', 'liability', 'credit', true, 'partner_loans', true, false, 'Plata que un socio le prestó a la SAS'),
        ('2.1.02.00.000', 'Previsiones', 'liability', 'credit', false, null, false, false, null),
        ('2.1.02.01.000', 'Previsión para despidos', 'liability', 'credit', true, null, false, false, 'Indemnizaciones posibles por despidos (la carga la contadora)'),
        ('2.2.00.00.000', 'Pasivo no corriente', 'liability', 'credit', false, null, false, false, null),
        ('2.2.01.00.000', 'Préstamos', 'liability', 'credit', false, null, false, false, null),
        ('2.2.01.01.000', 'Préstamos a largo plazo', 'liability', 'credit', false, null, false, false, null),
        ('2.2.01.01.001', 'Préstamos bancarios a largo plazo', 'liability', 'credit', true, null, false, false, 'Cuotas que vencen a más de un año'),
        ('3.0.00.00.000', 'PATRIMONIO NETO', 'equity', 'credit', false, null, false, false, null),
        ('3.1.00.00.000', 'Capital', 'equity', 'credit', false, null, false, false, null),
        ('3.1.01.00.000', 'Capital social', 'equity', 'credit', true, 'share_capital', false, false, 'El capital del estatuto'),
        ('3.1.02.00.000', 'Ajuste de capital', 'equity', 'credit', true, null, false, false, 'El ajuste por inflación del capital (lo carga la contadora)'),
        ('3.1.07.00.000', 'Aportes irrevocables', 'equity', 'credit', true, 'irrevocable_contributions', false, false, 'Aportes a cuenta de futuras suscripciones'),
        ('3.1.08.00.000', 'Socios: capital a integrar (regularizadora)', 'equity', 'debit', true, 'capital_receivable', false, false, 'Capital suscripto que los socios todavía no pusieron'),
        ('3.3.00.00.000', 'Reservas y resultados', 'equity', 'credit', false, null, false, false, null),
        ('3.3.01.00.000', 'Reserva legal', 'equity', 'credit', false, null, false, false, null),
        ('3.3.01.01.000', 'Reserva legal', 'equity', 'credit', true, 'legal_reserve', false, false, 'La define la asamblea'),
        ('3.3.02.00.000', 'Otras reservas', 'equity', 'credit', false, null, false, false, null),
        ('3.3.02.01.000', 'Reservas facultativas', 'equity', 'credit', true, null, false, false, 'Reservas que decide la reunión de socios'),
        ('3.3.03.00.000', 'Resultados no asignados', 'equity', 'credit', false, null, false, false, null),
        ('3.3.03.01.000', 'Resultados no asignados', 'equity', 'credit', true, 'retained_earnings', false, false, 'Ganancias o pérdidas de ejercicios anteriores'),
        ('3.3.03.03.000', 'Ajustes de ejercicios anteriores', 'equity', 'credit', true, null, false, false, 'Correcciones de ejercicios ya cerrados (las carga la contadora)'),
        ('3.3.03.04.000', 'Resultado del ejercicio', 'equity', 'credit', true, 'current_year_result', false, false, 'Lo deja la refundición al cerrar el ejercicio'),
        ('3.3.03.05.000', 'Saldo de apertura a asignar', 'equity', 'credit', true, 'opening_equity', false, false, 'La diferencia del asiento de apertura; la contadora la pasa a capital o resultados'),
        ('4.0.00.00.000', 'RESULTADO DEL EJERCICIO', 'income', 'credit', false, null, false, false, 'Ingresos menos egresos: su saldo es la ganancia (o la pérdida) del ejercicio'),
        ('4.1.00.00.000', 'INGRESOS', 'income', 'credit', false, null, false, false, null),
        ('4.1.01.00.000', 'Ventas', 'income', 'credit', false, null, false, false, null),
        ('4.1.01.01.000', 'Ventas del salón', 'income', 'credit', false, null, false, false, null),
        ('4.1.01.01.001', 'Ventas salón: facturadas', 'income', 'credit', true, 'sales_salon_invoiced', false, false, 'Neto de lo facturado en el salón (concilia con el Libro IVA ventas)'),
        ('4.1.01.01.002', 'Ventas salón: sin factura', 'income', 'credit', true, 'sales_salon_uninvoiced', false, false, 'Lo vendido en el salón que no se facturó (sin IVA débito)'),
        ('4.1.01.02.000', 'Ventas de delivery', 'income', 'credit', false, null, false, false, null),
        ('4.1.01.02.001', 'Ventas delivery: facturadas', 'income', 'credit', true, 'sales_delivery_invoiced', false, false, 'Neto de lo facturado por delivery'),
        ('4.1.01.02.002', 'Ventas delivery: sin factura', 'income', 'credit', true, 'sales_delivery_uninvoiced', false, false, 'Lo vendido por delivery que no se facturó'),
        ('4.1.01.03.000', 'Ventas de eventos y empresas', 'income', 'credit', false, null, false, false, null),
        ('4.1.01.03.001', 'Ventas eventos: facturadas', 'income', 'credit', true, 'sales_events_invoiced', false, false, 'Eventos y empresas facturados'),
        ('4.1.01.03.002', 'Ventas eventos: sin factura', 'income', 'credit', true, 'sales_events_uninvoiced', false, false, 'Eventos que no se facturaron'),
        ('4.1.02.00.000', 'Ingresos financieros', 'income', 'credit', false, null, false, false, null),
        ('4.1.02.01.000', 'Intereses ganados', 'income', 'credit', false, null, false, false, null),
        ('4.1.02.01.001', 'Intereses y rendimientos', 'income', 'credit', true, 'interest_income', false, false, 'Rendimientos de Mercado Pago, plazos fijos'),
        ('4.1.02.03.000', 'Otros ingresos financieros', 'income', 'credit', false, null, false, false, null),
        ('4.1.02.03.001', 'Descuentos obtenidos', 'income', 'credit', true, 'discounts_obtained', false, false, 'Bonificaciones y diferencias chicas a favor al pagar'),
        ('4.1.02.03.003', 'Resultado por exposición a la inflación (RECPAM)', 'income', 'credit', true, null, false, false, 'El ajuste por inflación de los estados contables (lo carga la contadora)'),
        ('4.1.03.00.000', 'Otros ingresos', 'income', 'credit', false, null, false, false, null),
        ('4.1.03.01.000', 'Otros ingresos', 'income', 'credit', false, null, false, false, null),
        ('4.1.03.01.001', 'Sobrantes de caja', 'income', 'credit', true, 'cash_over', false, false, 'Cuando al contar la caja hay más de lo que dice el sistema'),
        ('4.1.03.01.002', 'Ingresos varios', 'income', 'credit', true, 'other_income', false, false, 'Ingresos que no son ventas'),
        ('4.1.03.01.003', 'Recupero de gastos', 'income', 'credit', true, null, false, false, 'Gastos que te devuelven, por ejemplo un seguro que paga un arreglo'),
        ('4.1.03.01.004', 'Resultado por venta de bienes de uso', 'income', 'credit', true, null, false, false, 'Lo que se gana al vender un equipo o un mueble de la SAS (lo calcula la contadora)'),
        ('4.2.00.00.000', 'EGRESOS', 'expense', 'debit', false, null, false, false, null),
        ('4.2.01.00.000', 'Gastos de comercialización', 'expense', 'debit', false, null, false, false, null),
        ('4.2.01.01.000', 'Personal', 'expense', 'debit', false, null, false, false, null),
        ('4.2.01.01.003', 'Sueldos y jornales', 'expense', 'debit', true, 'salaries', false, false, 'Sueldos brutos (asiento mensual de la contadora)'),
        ('4.2.01.01.006', 'Contribuciones patronales', 'expense', 'debit', true, 'employer_contributions', false, false, 'Las cargas a cargo de la SAS'),
        ('4.2.01.01.008', 'Gratificaciones y premios', 'expense', 'debit', true, null, false, false, 'Premios y gratificaciones al personal (los liquida la contadora)'),
        ('4.2.01.01.010', 'ART y seguro de vida obligatorio', 'expense', 'debit', true, null, false, true, 'Seguro de riesgos del trabajo'),
        ('4.2.01.01.011', 'Personal eventual y extras', 'expense', 'debit', true, null, false, true, 'Extras de eventos, changas'),
        ('4.2.01.01.012', 'Uniformes y ropa de trabajo', 'expense', 'debit', true, null, false, true, 'Delantales, chaquetas y calzado de trabajo'),
        ('4.2.01.02.000', 'Impuestos, tasas y contribuciones', 'expense', 'debit', false, null, false, false, null),
        ('4.2.01.02.003', 'Impuesto a las ganancias', 'expense', 'debit', true, 'income_tax_expense', false, false, 'El impuesto del ejercicio (lo carga la contadora)'),
        ('4.2.01.02.005', 'Comercio e Industria', 'expense', 'debit', true, 'municipal_tax_expense', false, true, 'La contribución municipal sobre comercio e industria'),
        ('4.2.01.02.008', 'Impuesto de sellos', 'expense', 'debit', true, null, false, true, 'Sellos de Rentas por contratos, por ejemplo el alquiler'),
        ('4.2.01.02.010', 'Ingresos Brutos', 'expense', 'debit', true, 'iibb_expense', false, true, 'La declaración mensual de IIBB'),
        ('4.2.01.02.015', 'Otros impuestos y tasas', 'expense', 'debit', true, 'other_taxes_expense', false, true, 'Percepciones municipales y otros tributos'),
        ('4.2.01.03.000', 'Gastos del local', 'expense', 'debit', false, null, false, false, null),
        ('4.2.01.03.001', 'Mantenimiento y reparaciones', 'expense', 'debit', true, 'maintenance', false, true, 'Plomero, electricista, arreglos'),
        ('4.2.01.03.002', 'Amortizaciones', 'expense', 'debit', true, 'depreciation', false, false, 'La carga la contadora al cierre'),
        ('4.2.01.03.003', 'Telefonía', 'expense', 'debit', true, null, false, true, 'Celulares y teléfono fijo'),
        ('4.2.01.03.004', 'Energía eléctrica', 'expense', 'debit', true, null, false, true, 'Luz (EPEC)'),
        ('4.2.01.03.005', 'Gas', 'expense', 'debit', true, null, false, true, 'Gas natural o envasado'),
        ('4.2.01.03.006', 'Librería y papelería', 'expense', 'debit', true, null, false, true, 'Papel, rollos de ticketera'),
        ('4.2.01.03.008', 'Otra publicidad y promociones', 'expense', 'debit', true, 'advertising_other', false, true, 'Volantes, cartelería, promociones'),
        ('4.2.01.03.011', 'Software y suscripciones', 'expense', 'debit', true, null, false, true, 'Thinkeon, HUB, apps'),
        ('4.2.01.03.012', 'Alquiler', 'expense', 'debit', true, null, false, true, 'El alquiler del local'),
        ('4.2.01.03.014', 'Gastos varios', 'expense', 'debit', true, 'misc_expenses', false, true, 'Lo que no entra en otra cuenta'),
        ('4.2.01.03.016', 'Movilidad, fletes y envíos', 'expense', 'debit', true, null, false, true, 'Taxis, fletes, cadetería'),
        ('4.2.01.03.017', 'Atención a clientes y cortesías', 'expense', 'debit', true, null, false, true, 'Invitaciones, regalos y atenciones a clientes'),
        ('4.2.01.03.018', 'Deudores incobrables', 'expense', 'debit', true, null, false, false, 'Lo que un cliente ya no va a pagar (lo carga la contadora)'),
        ('4.2.01.03.022', 'Mantenimiento edilicio', 'expense', 'debit', true, null, false, true, 'Arreglos del edificio: pintura, techos, plomería grande'),
        ('4.2.01.03.024', 'Agua', 'expense', 'debit', true, null, false, true, 'Agua'),
        ('4.2.01.03.025', 'Internet', 'expense', 'debit', true, null, false, true, 'Internet del local'),
        ('4.2.01.03.027', 'Publicidad en redes (Meta, Google)', 'expense', 'debit', true, 'advertising_online', false, true, 'Pauta en redes, en pesos'),
        ('4.2.01.03.028', 'Faltantes de caja', 'expense', 'debit', true, 'cash_short', false, false, 'Cuando al contar la caja hay menos de lo que dice el sistema'),
        ('4.2.01.03.029', 'Limpieza e higiene', 'expense', 'debit', true, 'cleaning', false, true, 'Artículos de limpieza, fumigación'),
        ('4.2.01.03.030', 'Expensas', 'expense', 'debit', true, null, false, true, 'Expensas del local'),
        ('4.2.01.03.031', 'Seguridad y monitoreo', 'expense', 'debit', true, null, false, true, 'Alarma, vigilancia'),
        ('4.2.01.03.032', 'Música y derechos (SADAIC, AADI-CAPIF)', 'expense', 'debit', true, null, false, true, 'Derechos de música'),
        ('4.2.01.03.033', 'Vajilla y utensilios de reposición', 'expense', 'debit', true, null, false, true, 'Vasos, platos y utensilios que se rompen y se reponen seguido'),
        ('4.2.01.05.000', 'Comisiones y costos de cobro', 'expense', 'debit', false, null, false, false, null),
        ('4.2.01.05.001', 'Comisiones de tarjetas', 'expense', 'debit', true, 'fees_cards', false, false, 'Aranceles de débito y crédito'),
        ('4.2.01.05.002', 'Comisiones de Mercado Pago', 'expense', 'debit', true, 'fees_wallets', false, false, 'Comisión de QR y otras de Mercado Pago'),
        ('4.2.01.05.003', 'Comisiones de plataformas de delivery', 'expense', 'debit', true, 'fees_platforms', false, false, 'Comisión de PedidosYa, Rappi y las demás'),
        ('4.2.01.05.004', 'Costo financiero y otros cargos de cobro', 'expense', 'debit', true, 'fees_other', false, true, 'Cargos de cobro que no son comisión'),
        ('4.2.02.00.000', 'Gastos de administración', 'expense', 'debit', false, null, false, false, null),
        ('4.2.02.01.000', 'Honorarios', 'expense', 'debit', false, null, false, false, null),
        ('4.2.02.01.003', 'Honorarios contables', 'expense', 'debit', true, null, false, true, 'La contadora o el estudio contable'),
        ('4.2.02.01.006', 'Honorarios profesionales', 'expense', 'debit', true, null, false, true, 'Abogados, diseño, sistemas y otros profesionales'),
        ('4.2.02.04.000', 'Gastos bancarios y financieros', 'expense', 'debit', false, null, false, false, null),
        ('4.2.02.04.001', 'Intereses pagados', 'expense', 'debit', true, 'interest_expense', false, true, 'Intereses de préstamos y tarjetas'),
        ('4.2.02.04.003', 'Gastos bancarios', 'expense', 'debit', true, 'bank_fees', false, true, 'Mantenimiento de cuenta y comisiones del banco'),
        ('4.2.02.04.004', 'Intereses y multas fiscales', 'expense', 'debit', true, 'tax_penalties', false, true, 'Recargos por pagar tarde'),
        ('4.2.02.04.005', 'Diferencias de cambio', 'expense', 'debit', true, null, false, false, 'Lo que se pierde por la variación del dólar (lo carga la contadora)'),
        ('4.2.02.04.006', 'Impuesto sobre débitos y créditos bancarios', 'expense', 'debit', true, 'bank_tax_expense', false, false, 'La parte del impuesto al cheque que no se computa en Ganancias'),
        ('4.2.02.05.000', 'Seguros', 'expense', 'debit', false, null, false, false, null),
        ('4.2.02.05.001', 'Seguros', 'expense', 'debit', true, null, false, true, 'Seguro integral del local y otros seguros'),
        ('4.2.03.00.000', 'Costo de mercadería vendida', 'expense', 'debit', false, null, false, false, null),
        ('4.2.03.01.000', 'Costo de mercadería vendida', 'expense', 'debit', true, null, false, false, 'Existencia inicial más compras menos existencia final (lo calcula la contadora al cierre)'),
        ('4.2.03.02.000', 'Variación de existencias', 'expense', 'debit', true, 'inventory_variation', false, false, 'La carga la contadora al cierre'),
        ('5.0.00.00.000', 'COMPRAS', 'expense', 'debit', false, null, false, false, 'Lo que comprás para vender o elaborar; al cierre la contadora lo lleva al costo de mercadería vendida'),
        ('5.1.00.00.000', 'Compras de mercadería e insumos', 'expense', 'debit', false, null, false, false, null),
        ('5.1.01.00.000', 'Compras de mercadería', 'expense', 'debit', false, null, false, false, null),
        ('5.1.01.01.000', 'Alimentos y bebidas', 'expense', 'debit', false, null, false, false, null),
        ('5.1.01.01.001', 'Compras: alimentos', 'expense', 'debit', true, 'purchases_food', false, true, 'Carne, verdura, almacén'),
        ('5.1.01.01.002', 'Compras: bebidas sin alcohol', 'expense', 'debit', true, 'purchases_soft_drinks', false, true, 'Gaseosas, aguas, jugos'),
        ('5.1.01.01.003', 'Compras: bebidas con alcohol', 'expense', 'debit', true, 'purchases_alcohol', false, true, 'Cervezas, vinos, bebidas blancas'),
        ('5.1.01.01.004', 'Compras: café e infusiones', 'expense', 'debit', true, 'purchases_coffee', false, true, 'Café, té, yerba'),
        ('5.1.01.01.005', 'Compras: panadería y pastelería', 'expense', 'debit', true, 'purchases_bakery', false, true, 'Panes, facturas, tortas compradas'),
        ('5.1.01.02.000', 'Insumos y descartables', 'expense', 'debit', false, null, false, false, null),
        ('5.1.01.02.001', 'Compras: descartables y packaging', 'expense', 'debit', true, 'purchases_packaging', false, true, 'Vasos, envases, bolsas de delivery'),
        ('5.1.01.02.002', 'Compras: otros insumos', 'expense', 'debit', true, 'purchases_other', false, true, 'Hielo y otros insumos de cocina y barra')
        -- @acc-seed-chart:end
      ) as c(code, name, type, normal_side, postable, system_key, requires_party, purchase_selectable, description)
     where private.acc_code_depth(c.code) = v_level
     order by c.code
    on conflict (tenant_id, code) do nothing;
    get diagnostics v_n = row_count;
    v_total := v_total + v_n;
  end loop;
  return v_total;
end;
$$;

comment on function private.acc_seed_chart(uuid) is
  'Siembra el plan de cuentas estándar (#16, estilo del modelo de 5 niveles) por profundidad. Idempotente por (tenant_id, code). Devuelve cuántas cuentas insertó.';

revoke all on function private.acc_seed_chart(uuid) from public, anon, authenticated;
