import {
  ArrowUpRight,
  Banknote,
  BarChart3,
  BookOpen,
  BookText,
  CalendarCheck,
  CalendarDays,
  ChefHat,
  ClipboardList,
  Coins,
  FileCode2,
  Gift,
  HandCoins,
  Handshake,
  Inbox,
  Landmark,
  LayoutDashboard,
  LayoutGrid,
  Link2,
  ListChecks,
  ListTree,
  type LucideIcon,
  Megaphone,
  MessageCircle,
  MessageSquareText,
  MonitorSmartphone,
  PartyPopper,
  QrCode,
  Receipt,
  ScanLine,
  Settings2,
  Sparkles,
  Stamp,
  Star,
  Tag,
  Truck,
  Users,
  UsersRound,
  UtensilsCrossed,
  Wallet,
  Workflow,
  Zap,
} from 'lucide-react'

/**
 * Map keys → componentes Lucide para el sidebar y el command palette.
 * Mantenemos las KEYS como literales serializables (string) para poder
 * pasarlos de Server Components a Client Components sin romper la
 * frontera RSC. El mapping vive solo en el cliente que renderiza.
 */
export const NAV_ICONS = {
  ArrowUpRight,
  Banknote,
  BarChart3,
  BookOpen,
  BookText,
  CalendarCheck,
  CalendarDays,
  ChefHat,
  ClipboardList,
  Coins,
  FileCode2,
  Gift,
  HandCoins,
  Handshake,
  Inbox,
  Landmark,
  LayoutDashboard,
  LayoutGrid,
  Link2,
  ListChecks,
  ListTree,
  Megaphone,
  MessageCircle,
  MessageSquareText,
  MonitorSmartphone,
  PartyPopper,
  QrCode,
  Receipt,
  ScanLine,
  Settings2,
  Sparkles,
  Stamp,
  Star,
  Tag,
  Truck,
  Users,
  UsersRound,
  UtensilsCrossed,
  Wallet,
  Workflow,
  Zap,
} satisfies Record<string, LucideIcon>

export type NavIconKey = keyof typeof NAV_ICONS
